# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'Ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  workingDirectory: backend/QandA
  displayName: 'backend build'

- script: dotnet test
  workingDirectory: backend/BackendTests
  displayName: 'backend tests'

- script: dotnet publish --configuration $(buildConfiguration)
  workingDirectory: backend
  displayName: 'backend publish'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'backend/QandA/bin/Release/net8.0/publish' 
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/backend/$(Build.BuildId).zip'
    replaceExistingArchive: true 
  displayName: 'backend zip files'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/backend' 
    artifactName: 'backend/QandA' 
  displayName: 'backend publish to pipeline'

- script: npm install
  workingDirectory: frontend
  displayName: 'frontend install dependencies'

- script: npm run test:ci
  workingDirectory: frontend
  displayName: 'frontend tests'

- script: npm run build:staging
  workingDirectory: frontend
  displayName: 'frontend staging build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'frontend/build'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/frontend-staging/build.zip'
    replaceExistingArchive: true 
  displayName: 'frontend staging zip files'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'frontend/cypress' 
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/frontend-staging/tests.zip'
    replaceExistingArchive: true 
  displayName: 'frontend cypress zip files'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/frontend-staging' 
    artifactName: 'frontend-staging' 
  displayName: 'frontend staging publish to pipeline'

- script: npm run build:production
  workingDirectory: frontend
  displayName: 'frontend production build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'frontend/build' 
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/frontend-production/build.zip'
    replaceExistingArchive: true 
  displayName: 'frontend production zip files'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/frontend-production' 
    artifactName: 'frontend-production' 
  displayName: 'frontend production publish to pipeline'